#!/bin/sh
set -e

case "$1" in
    configure)
      echo "Install pysodium"
      pip install -I pysodium==0.6.6
      exit 0
      ;;

    upgrade)
        # Upgrade package
        exit 0
        ;;

    *)
        exit 0
        ;;
esac

exit 0